2024-11-22 16:13:25,730 ||| WARNING ||| Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "F:\PyProjects\Project_VENV\urban\tests_12_4.py", line 85, in test_run
    runner_2 = Runner(None)
               ^^^^^^^^^^^^
  File "F:\PyProjects\Project_VENV\urban\tests_12_4.py", line 14, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано NoneType
2024-11-22 16:13:25,730 ||| WARNING ||| Неверная скорость для Runner
Traceback (most recent call last):
  File "F:\PyProjects\Project_VENV\urban\tests_12_4.py", line 70, in test_walk
    runner_1 = Runner('num_1', speed=-9)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PyProjects\Project_VENV\urban\tests_12_4.py", line 19, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -9
